review #1
difiozy/pet-students pull request #2
Opened 2023-09-30 15:21 UTC by Ps1Hhh

2023-09-30 15:35 UTC, difiozy requested changes

2023-09-30 15:35 UTC, difiozy commented on pom.xml
> +            <artifactId>spring-boot-starter-data-jpa</artifactId>
повторяется зависимость

2023-09-30 15:35 UTC, difiozy commented on pom.xml
> +        <dependency>
Нужно выбрать что то одно либо jdbc или jpa

2023-09-30 15:35 UTC, difiozy commented on src/main/java/esipov/controllers/BlogController.java
> +    @GetMapping("/blog")
/blog нужно перенести в RequestMapping над контроллеров

2023-09-30 15:35 UTC, difiozy commented on src/main/java/esipov/controllers/BlogController.java
> +    public String blogMain(Model model){
Этот метод работае как должен?

2023-09-30 15:35 UTC, difiozy commented on src/main/java/esipov/controllers/MainController.java
> +public class MainController {
Нужно более осмысленное название

2023-09-30 15:35 UTC, difiozy commented on src/main/java/esipov/controllers/BlogController.java
> +        Iterable<Post> posts = postRepository.findAll();
Напрямую использовать репозиторий в контроллере не стоит, нужен слой сервиса, придершивайся подхода MVC

2023-09-30 15:35 UTC, difiozy commented on src/main/java/esipov/controllers/PostController.java
> +@RequestMapping("/api/")
Преписка v1 в конце

2023-09-30 15:35 UTC, difiozy commented on src/main/java/esipov/controllers/PostController.java
> +/*
Не стоит коллекционировать код

2023-09-30 15:35 UTC, difiozy commented on src/main/java/esipov/controllers/PostController.java
> +    public ResponseEntity<Post> getPostById(@PathVariable Long id) {
Думаю тут тебе не нужен ResponseEntity

2023-10-01 12:53 UTC, Ps1Hhh commented on pom.xml
> +            <artifactId>spring-boot-starter-data-jpa</artifactId>
исправил

2023-10-01 12:53 UTC, Ps1Hhh commented on pom.xml
> +        <dependency>
оставил jpa

2023-10-01 12:55 UTC, Ps1Hhh commented on src/main/java/esipov/controllers/BlogController.java
> +    public String blogMain(Model model){
вообще да, но он бесполезный, я уберу его потом

2023-10-01 12:56 UTC, Ps1Hhh commented on src/main/java/esipov/controllers/PostController.java
> +@RequestMapping("/api/")
исправил

2023-10-12 16:40 UTC, Ps1Hhh commented on src/main/java/esipov/controllers/MainController.java
> +public class MainController {
Пересмотрел взгляд и удалил ибо это не надо мне сейчас, а изначально надо было чтобы просто понять как работает это гогно

2023-10-12 16:40 UTC, Ps1Hhh commented on src/main/java/esipov/controllers/BlogController.java
> +        Iterable<Post> posts = postRepository.findAll();
тоже нахуй удалил ибо не надо

2023-10-12 16:42 UTC, Ps1Hhh commented on src/main/java/esipov/controllers/PostController.java
> +/*
убрал

2023-10-12 16:47 UTC, Ps1Hhh commented on src/main/java/esipov/controllers/PostController.java
> +    public ResponseEntity<Post> getPostById(@PathVariable Long id) {
Убрал их все)

2023-10-12 17:58 UTC, difiozy requested changes

2023-10-12 17:58 UTC, difiozy commented on src/main/java/esipov/controllers/PostController.java
> +        return "blog-main";
нужно удалить

2023-10-12 17:58 UTC, difiozy commented on src/main/java/esipov/controllers/PostController.java
> +@RequestMapping("/api/")
добавиь v1 в конце и стоит убрать / в конце

2023-10-12 17:58 UTC, difiozy commented on src/main/java/esipov/controllers/PostController.java
> +    @GetMapping("/posts")
Заметь, у тебя /posts общий для всех методов, его стоит вынести в RequestMapping

2023-10-12 18:16 UTC, Ps1Hhh commented on src/main/java/esipov/controllers/PostController.java
> +        return "blog-main";
убрал

2023-10-12 18:16 UTC, Ps1Hhh commented on src/main/java/esipov/controllers/PostController.java
> +@RequestMapping("/api/")
Сделал

2023-10-12 18:16 UTC, Ps1Hhh commented on src/main/java/esipov/controllers/PostController.java
> +    @GetMapping("/posts")
исправил

2023-10-13 19:18 UTC, difiozy approved these changes

2023-10-13 19:20 UTC, merged